# Generated by Django 6.0.1 on 2026-01-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'start_time', 'queue_position']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('approved', 'Approved'), ('disapproved', 'Disapproved'), ('finished', 'Finished')], default='queued', max_length=20),
        ),
    ]
